// loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER'
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER'
export const GET_PRODUCTS_ENABLE_LOADER = 'GET_PRODUCTS_ENABLE_LOADER'
export const GET_PRODUCTS_DISABLE_LOADER = 'GET_PRODUCTS_DISABLE_LOADER'

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_LOGOUT = 'LOGIN_LOGOUT'

// products
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST'
export const GET_PRODUCTS_RESPONSE = 'GET_PRODUCTS_RESPONSE'
